apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample-app
spec:
  selector:
    matchLabels:
      app: nginx-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-sample-app
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-app-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-sample-app
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-sample-app-ingress
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx.johnnymom.com
    secretName: nginx-johnnymom-com-cert # < cert-manager will store the created certificate in this secret.

  rules:
  - host: nginx.johnnymom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-sample-app-service
            port:
              number: 80
